target_dir:
  - '~/Downloads'
  - '~/Desktop'
outdir: '~/housekeep/'
exts:
  csv: csv
  dmg: dmg
  doc: doc
  docx: doc
  drawio: drawio
  jpg: jpg
  jpeg: jpg
  json: json
  log: log
  m4a: m4a
  pdf: pdf
  png: png
  ppt: ppt
  pptx: ppt
  py: py
  txt: txt
  xls: xls
  xlsx: xls
  yaml: yml
  yml: yml
  zip: zip
  tar.gz : tar
  tgz : tar
  md: md
  other: other
